### ISSUE TITLE
Improvements to Unit and Integration Testing

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#535]
Checklist for issues having to do with unit tests:

- [x] Move test data to JLAB (#437)

- [x] Disable more tests in default build (#501) 

- [x] Remove test data module (#406)

- [x] Remove unnecessary print outs from tests and ITs

- [x] Reduce number of events used in recon ITs (coordinate with @normangraf)

- [x] Remove out-of-date tests or those which do not really test anything
